pre-commit:
  parallel: true
  jobs:
    - name: lint
      glob: "*.go"
      env:
        GOWORK: off
      run: ./.lint.sh
    - name: fmt
      glob: "*.go"
      env:
       GOWORK: off
      run: golangci-lint fmt {staged_files}
#    - name: buf-format
#      glob: "*.proto"
#      run: buf format -w {staged_files}