// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BooksColumns holds the columns for the "books" table.
	BooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "abstract", Type: field.TypeString, Nullable: true},
		{Name: "author", Type: field.TypeString, Nullable: true},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BooksTable holds the schema information for the "books" table.
	BooksTable = &schema.Table{
		Name:       "books",
		Columns:    BooksColumns,
		PrimaryKey: []*schema.Column{BooksColumns[0]},
	}
	// BookShelvesColumns holds the columns for the "book_shelves" table.
	BookShelvesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BookShelvesTable holds the schema information for the "book_shelves" table.
	BookShelvesTable = &schema.Table{
		Name:       "book_shelves",
		Columns:    BookShelvesColumns,
		PrimaryKey: []*schema.Column{BookShelvesColumns[0]},
	}
	// BookRelShelvesColumns holds the columns for the "book_rel_shelves" table.
	BookRelShelvesColumns = []*schema.Column{
		{Name: "book_id", Type: field.TypeInt64},
		{Name: "book_shelf_id", Type: field.TypeInt64},
	}
	// BookRelShelvesTable holds the schema information for the "book_rel_shelves" table.
	BookRelShelvesTable = &schema.Table{
		Name:       "book_rel_shelves",
		Columns:    BookRelShelvesColumns,
		PrimaryKey: []*schema.Column{BookRelShelvesColumns[0], BookRelShelvesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "book_rel_shelves_book_id",
				Columns:    []*schema.Column{BookRelShelvesColumns[0]},
				RefColumns: []*schema.Column{BooksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "book_rel_shelves_book_shelf_id",
				Columns:    []*schema.Column{BookRelShelvesColumns[1]},
				RefColumns: []*schema.Column{BookShelvesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BooksTable,
		BookShelvesTable,
		BookRelShelvesTable,
	}
)

func init() {
	BookRelShelvesTable.ForeignKeys[0].RefTable = BooksTable
	BookRelShelvesTable.ForeignKeys[1].RefTable = BookShelvesTable
}
