// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/syralon/coconut/example/ent/book"
	"github.com/syralon/coconut/example/ent/bookshelf"
	"github.com/syralon/coconut/example/ent/predicate"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdate) SetTitle(v string) *BookUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAbstract sets the "abstract" field.
func (_u *BookUpdate) SetAbstract(v string) *BookUpdate {
	_u.mutation.SetAbstract(v)
	return _u
}

// SetNillableAbstract sets the "abstract" field if the given value is not nil.
func (_u *BookUpdate) SetNillableAbstract(v *string) *BookUpdate {
	if v != nil {
		_u.SetAbstract(*v)
	}
	return _u
}

// ClearAbstract clears the value of the "abstract" field.
func (_u *BookUpdate) ClearAbstract() *BookUpdate {
	_u.mutation.ClearAbstract()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *BookUpdate) SetAuthor(v string) *BookUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *BookUpdate) SetNillableAuthor(v *string) *BookUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *BookUpdate) ClearAuthor() *BookUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// SetCover sets the "cover" field.
func (_u *BookUpdate) SetCover(v string) *BookUpdate {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCover(v *string) *BookUpdate {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *BookUpdate) ClearCover() *BookUpdate {
	_u.mutation.ClearCover()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BookUpdate) SetCreatedAt(v time.Time) *BookUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCreatedAt(v *time.Time) *BookUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdate) SetUpdatedAt(v time.Time) *BookUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRelShelfIDs adds the "rel_shelves" edge to the BookShelf entity by IDs.
func (_u *BookUpdate) AddRelShelfIDs(ids ...int64) *BookUpdate {
	_u.mutation.AddRelShelfIDs(ids...)
	return _u
}

// AddRelShelves adds the "rel_shelves" edges to the BookShelf entity.
func (_u *BookUpdate) AddRelShelves(v ...*BookShelf) *BookUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelShelfIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// ClearRelShelves clears all "rel_shelves" edges to the BookShelf entity.
func (_u *BookUpdate) ClearRelShelves() *BookUpdate {
	_u.mutation.ClearRelShelves()
	return _u
}

// RemoveRelShelfIDs removes the "rel_shelves" edge to BookShelf entities by IDs.
func (_u *BookUpdate) RemoveRelShelfIDs(ids ...int64) *BookUpdate {
	_u.mutation.RemoveRelShelfIDs(ids...)
	return _u
}

// RemoveRelShelves removes "rel_shelves" edges to BookShelf entities.
func (_u *BookUpdate) RemoveRelShelves(v ...*BookShelf) *BookUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelShelfIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Abstract(); ok {
		_spec.SetField(book.FieldAbstract, field.TypeString, value)
	}
	if _u.mutation.AbstractCleared() {
		_spec.ClearField(book.FieldAbstract, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(book.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(book.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(book.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RelShelvesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.RelShelvesTable,
			Columns: book.RelShelvesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelShelvesIDs(); len(nodes) > 0 && !_u.mutation.RelShelvesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.RelShelvesTable,
			Columns: book.RelShelvesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelShelvesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.RelShelvesTable,
			Columns: book.RelShelvesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetTitle sets the "title" field.
func (_u *BookUpdateOne) SetTitle(v string) *BookUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAbstract sets the "abstract" field.
func (_u *BookUpdateOne) SetAbstract(v string) *BookUpdateOne {
	_u.mutation.SetAbstract(v)
	return _u
}

// SetNillableAbstract sets the "abstract" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableAbstract(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetAbstract(*v)
	}
	return _u
}

// ClearAbstract clears the value of the "abstract" field.
func (_u *BookUpdateOne) ClearAbstract() *BookUpdateOne {
	_u.mutation.ClearAbstract()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *BookUpdateOne) SetAuthor(v string) *BookUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableAuthor(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *BookUpdateOne) ClearAuthor() *BookUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// SetCover sets the "cover" field.
func (_u *BookUpdateOne) SetCover(v string) *BookUpdateOne {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCover(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *BookUpdateOne) ClearCover() *BookUpdateOne {
	_u.mutation.ClearCover()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BookUpdateOne) SetCreatedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCreatedAt(v *time.Time) *BookUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdateOne) SetUpdatedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRelShelfIDs adds the "rel_shelves" edge to the BookShelf entity by IDs.
func (_u *BookUpdateOne) AddRelShelfIDs(ids ...int64) *BookUpdateOne {
	_u.mutation.AddRelShelfIDs(ids...)
	return _u
}

// AddRelShelves adds the "rel_shelves" edges to the BookShelf entity.
func (_u *BookUpdateOne) AddRelShelves(v ...*BookShelf) *BookUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelShelfIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// ClearRelShelves clears all "rel_shelves" edges to the BookShelf entity.
func (_u *BookUpdateOne) ClearRelShelves() *BookUpdateOne {
	_u.mutation.ClearRelShelves()
	return _u
}

// RemoveRelShelfIDs removes the "rel_shelves" edge to BookShelf entities by IDs.
func (_u *BookUpdateOne) RemoveRelShelfIDs(ids ...int64) *BookUpdateOne {
	_u.mutation.RemoveRelShelfIDs(ids...)
	return _u
}

// RemoveRelShelves removes "rel_shelves" edges to BookShelf entities.
func (_u *BookUpdateOne) RemoveRelShelves(v ...*BookShelf) *BookUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelShelfIDs(ids...)
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Abstract(); ok {
		_spec.SetField(book.FieldAbstract, field.TypeString, value)
	}
	if _u.mutation.AbstractCleared() {
		_spec.ClearField(book.FieldAbstract, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(book.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(book.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(book.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RelShelvesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.RelShelvesTable,
			Columns: book.RelShelvesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelShelvesIDs(); len(nodes) > 0 && !_u.mutation.RelShelvesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.RelShelvesTable,
			Columns: book.RelShelvesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelShelvesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.RelShelvesTable,
			Columns: book.RelShelvesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
