// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/syralon/coconut/example/ent/bookshelf"
	"github.com/syralon/coconut/example/ent/predicate"
)

// BookShelfDelete is the builder for deleting a BookShelf entity.
type BookShelfDelete struct {
	config
	hooks    []Hook
	mutation *BookShelfMutation
}

// Where appends a list predicates to the BookShelfDelete builder.
func (_d *BookShelfDelete) Where(ps ...predicate.BookShelf) *BookShelfDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BookShelfDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BookShelfDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BookShelfDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bookshelf.Table, sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BookShelfDeleteOne is the builder for deleting a single BookShelf entity.
type BookShelfDeleteOne struct {
	_d *BookShelfDelete
}

// Where appends a list predicates to the BookShelfDelete builder.
func (_d *BookShelfDeleteOne) Where(ps ...predicate.BookShelf) *BookShelfDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BookShelfDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bookshelf.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BookShelfDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
