// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/syralon/coconut/example/ent/book"
	"github.com/syralon/coconut/example/ent/bookshelf"
	"github.com/syralon/coconut/example/ent/predicate"
)

// BookShelfUpdate is the builder for updating BookShelf entities.
type BookShelfUpdate struct {
	config
	hooks    []Hook
	mutation *BookShelfMutation
}

// Where appends a list predicates to the BookShelfUpdate builder.
func (_u *BookShelfUpdate) Where(ps ...predicate.BookShelf) *BookShelfUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *BookShelfUpdate) SetName(v string) *BookShelfUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BookShelfUpdate) SetNillableName(v *string) *BookShelfUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BookShelfUpdate) SetCreatedAt(v time.Time) *BookShelfUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BookShelfUpdate) SetNillableCreatedAt(v *time.Time) *BookShelfUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookShelfUpdate) SetUpdatedAt(v time.Time) *BookShelfUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (_u *BookShelfUpdate) AddBookIDs(ids ...int64) *BookShelfUpdate {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBooks adds the "books" edges to the Book entity.
func (_u *BookShelfUpdate) AddBooks(v ...*Book) *BookShelfUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// Mutation returns the BookShelfMutation object of the builder.
func (_u *BookShelfUpdate) Mutation() *BookShelfMutation {
	return _u.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (_u *BookShelfUpdate) ClearBooks() *BookShelfUpdate {
	_u.mutation.ClearBooks()
	return _u
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (_u *BookShelfUpdate) RemoveBookIDs(ids ...int64) *BookShelfUpdate {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBooks removes "books" edges to Book entities.
func (_u *BookShelfUpdate) RemoveBooks(v ...*Book) *BookShelfUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookShelfUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookShelfUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookShelfUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookShelfUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookShelfUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bookshelf.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BookShelfUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bookshelf.Table, bookshelf.Columns, sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bookshelf.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bookshelf.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bookshelf.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   bookshelf.BooksTable,
			Columns: bookshelf.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBooksIDs(); len(nodes) > 0 && !_u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   bookshelf.BooksTable,
			Columns: bookshelf.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   bookshelf.BooksTable,
			Columns: bookshelf.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookshelf.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookShelfUpdateOne is the builder for updating a single BookShelf entity.
type BookShelfUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookShelfMutation
}

// SetName sets the "name" field.
func (_u *BookShelfUpdateOne) SetName(v string) *BookShelfUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BookShelfUpdateOne) SetNillableName(v *string) *BookShelfUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BookShelfUpdateOne) SetCreatedAt(v time.Time) *BookShelfUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BookShelfUpdateOne) SetNillableCreatedAt(v *time.Time) *BookShelfUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookShelfUpdateOne) SetUpdatedAt(v time.Time) *BookShelfUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (_u *BookShelfUpdateOne) AddBookIDs(ids ...int64) *BookShelfUpdateOne {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBooks adds the "books" edges to the Book entity.
func (_u *BookShelfUpdateOne) AddBooks(v ...*Book) *BookShelfUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// Mutation returns the BookShelfMutation object of the builder.
func (_u *BookShelfUpdateOne) Mutation() *BookShelfMutation {
	return _u.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (_u *BookShelfUpdateOne) ClearBooks() *BookShelfUpdateOne {
	_u.mutation.ClearBooks()
	return _u
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (_u *BookShelfUpdateOne) RemoveBookIDs(ids ...int64) *BookShelfUpdateOne {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBooks removes "books" edges to Book entities.
func (_u *BookShelfUpdateOne) RemoveBooks(v ...*Book) *BookShelfUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// Where appends a list predicates to the BookShelfUpdate builder.
func (_u *BookShelfUpdateOne) Where(ps ...predicate.BookShelf) *BookShelfUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookShelfUpdateOne) Select(field string, fields ...string) *BookShelfUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BookShelf entity.
func (_u *BookShelfUpdateOne) Save(ctx context.Context) (*BookShelf, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookShelfUpdateOne) SaveX(ctx context.Context) *BookShelf {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookShelfUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookShelfUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookShelfUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bookshelf.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BookShelfUpdateOne) sqlSave(ctx context.Context) (_node *BookShelf, err error) {
	_spec := sqlgraph.NewUpdateSpec(bookshelf.Table, bookshelf.Columns, sqlgraph.NewFieldSpec(bookshelf.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BookShelf.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookshelf.FieldID)
		for _, f := range fields {
			if !bookshelf.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bookshelf.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(bookshelf.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bookshelf.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bookshelf.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   bookshelf.BooksTable,
			Columns: bookshelf.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBooksIDs(); len(nodes) > 0 && !_u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   bookshelf.BooksTable,
			Columns: bookshelf.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   bookshelf.BooksTable,
			Columns: bookshelf.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BookShelf{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookshelf.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
