// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/syralon/coconut/example/ent/book"
	"github.com/syralon/coconut/example/ent/bookshelf"
	"github.com/syralon/coconut/example/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescCreatedAt is the schema descriptor for created_at field.
	bookDescCreatedAt := bookFields[5].Descriptor()
	// book.DefaultCreatedAt holds the default value on creation for the created_at field.
	book.DefaultCreatedAt = bookDescCreatedAt.Default.(func() time.Time)
	// bookDescUpdatedAt is the schema descriptor for updated_at field.
	bookDescUpdatedAt := bookFields[6].Descriptor()
	// book.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	book.DefaultUpdatedAt = bookDescUpdatedAt.Default.(func() time.Time)
	// book.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	book.UpdateDefaultUpdatedAt = bookDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookDescID is the schema descriptor for id field.
	bookDescID := bookFields[0].Descriptor()
	// book.DefaultID holds the default value on creation for the id field.
	book.DefaultID = bookDescID.Default.(func() int64)
	bookshelfFields := schema.BookShelf{}.Fields()
	_ = bookshelfFields
	// bookshelfDescCreatedAt is the schema descriptor for created_at field.
	bookshelfDescCreatedAt := bookshelfFields[2].Descriptor()
	// bookshelf.DefaultCreatedAt holds the default value on creation for the created_at field.
	bookshelf.DefaultCreatedAt = bookshelfDescCreatedAt.Default.(func() time.Time)
	// bookshelfDescUpdatedAt is the schema descriptor for updated_at field.
	bookshelfDescUpdatedAt := bookshelfFields[3].Descriptor()
	// bookshelf.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bookshelf.DefaultUpdatedAt = bookshelfDescUpdatedAt.Default.(func() time.Time)
	// bookshelf.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bookshelf.UpdateDefaultUpdatedAt = bookshelfDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookshelfDescID is the schema descriptor for id field.
	bookshelfDescID := bookshelfFields[0].Descriptor()
	// bookshelf.DefaultID holds the default value on creation for the id field.
	bookshelf.DefaultID = bookshelfDescID.Default.(func() int64)
}
