// Code generated by ent, DO NOT EDIT.

package book

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the book type in the database.
	Label = "book"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldAbstract holds the string denoting the abstract field in the database.
	FieldAbstract = "abstract"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldCover holds the string denoting the cover field in the database.
	FieldCover = "cover"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRelShelves holds the string denoting the rel_shelves edge name in mutations.
	EdgeRelShelves = "rel_shelves"
	// Table holds the table name of the book in the database.
	Table = "books"
	// RelShelvesTable is the table that holds the rel_shelves relation/edge. The primary key declared below.
	RelShelvesTable = "book_rel_shelves"
	// RelShelvesInverseTable is the table name for the BookShelf entity.
	// It exists in this package in order to avoid circular dependency with the "bookshelf" package.
	RelShelvesInverseTable = "book_shelves"
)

// Columns holds all SQL columns for book fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldAbstract,
	FieldAuthor,
	FieldCover,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// RelShelvesPrimaryKey and RelShelvesColumn2 are the table columns denoting the
	// primary key for the rel_shelves relation (M2M).
	RelShelvesPrimaryKey = []string{"book_id", "book_shelf_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() int64
)

// OrderOption defines the ordering options for the Book queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByAbstract orders the results by the abstract field.
func ByAbstract(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbstract, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByCover orders the results by the cover field.
func ByCover(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCover, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRelShelvesCount orders the results by rel_shelves count.
func ByRelShelvesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRelShelvesStep(), opts...)
	}
}

// ByRelShelves orders the results by rel_shelves terms.
func ByRelShelves(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRelShelvesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRelShelvesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RelShelvesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, RelShelvesTable, RelShelvesPrimaryKey...),
	)
}
